// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEuc3jiZNYQ4pwi4eeZ_tave9QzZBf6bM',
    appId: '1:517313251212:web:8903c882e50857d67bb8a9',
    messagingSenderId: '517313251212',
    projectId: 'fitness-app-35ae7',
    authDomain: 'fitness-app-35ae7.firebaseapp.com',
    storageBucket: 'fitness-app-35ae7.firebasestorage.app',
    measurementId: 'G-81L39DLY92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNIewXjFEY1FYnjd8F7jS1EG0snv9TkEs',
    appId: '1:517313251212:android:187eb1e3bfac6f7a7bb8a9',
    messagingSenderId: '517313251212',
    projectId: 'fitness-app-35ae7',
    storageBucket: 'fitness-app-35ae7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDExKyV4ISmf18HnX8p6DICDFjrmu_377Q',
    appId: '1:517313251212:ios:758f831f442accfb7bb8a9',
    messagingSenderId: '517313251212',
    projectId: 'fitness-app-35ae7',
    storageBucket: 'fitness-app-35ae7.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDExKyV4ISmf18HnX8p6DICDFjrmu_377Q',
    appId: '1:517313251212:ios:758f831f442accfb7bb8a9',
    messagingSenderId: '517313251212',
    projectId: 'fitness-app-35ae7',
    storageBucket: 'fitness-app-35ae7.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEuc3jiZNYQ4pwi4eeZ_tave9QzZBf6bM',
    appId: '1:517313251212:web:61ca8bb4ef120d1a7bb8a9',
    messagingSenderId: '517313251212',
    projectId: 'fitness-app-35ae7',
    authDomain: 'fitness-app-35ae7.firebaseapp.com',
    storageBucket: 'fitness-app-35ae7.firebasestorage.app',
    measurementId: 'G-ENL2GVLXQZ',
  );
}
